### ISSUE TITLE
Category id

### ISSUE THREAD

**Issue by Saurabh-Srivastava1** [uark-cviu/ASPIRe#1]
Hi,
Thank you for sharing this dataset. I am encountering some difficulties in mapping the category IDs in the annotations to their corresponding class labels. Could you please provide guidance on how to perform this mapping and indicate where I can find the necessary information?

**Comment by trongthuan205** [comment]
Thank you for raising your concern about our dataset.

In the annotations file, we have two keys: `dataset['thing_classes']` and `dataset['stuff_classes']`. These contain class names for object (`thing`) categories and stuff (`stuff`) categories. 

To get the complete list of classes, you need to combine these two lists:

```python
CLASSES = dataset['thing_classes'] + dataset['stuff_classes']
```

This will give you a single list `CLASSES` containing all the class names from `thing_classes` and `stuff_classes`.

With this `CLASSES` list, you can map the subject and object annotations to their corresponding class indices by finding the index of the class name in the `CLASSES` list.
